version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: api-go-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_finance
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
